language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install msgpack-python pylint==1.8.3 sphinx sphinx-rtd-theme websocket-client

script:
  - pylint --rcfile .pylintrc advancedhttpserver.py
  - python -m unittest -v tests
  - sphinx-build -b html -E docs/source docs/html
